export interface ParsedEIP681 {
  contractAddress: string;
  chainId: number;
  merchantWallet: string;
  amountPXO: string;
  label: string | null;
  paymentId: string | null;
}

/**
 * Parse an EIP-681 URI for an ERC-20 transfer call. Returns null if the URI
 * does not match the expected shape generated by api-pagos. Mirror of the
 * parser in `apps/api-pagos/src/lib/eip681.ts`.
 */
export function parseEIP681Uri(uri: string): ParsedEIP681 | null {
  const trimmed = uri.trim();
  const match = trimmed.match(/^ethereum:(0x[a-fA-F0-9]{40})@(\d+)\/transfer\?(.*)$/);
  if (!match) return null;

  const [, contractAddress, chainIdStr, qs] = match;
  const params = new URLSearchParams(qs);

  const merchantWallet = params.get('address');
  const amountPXO = params.get('uint256');
  if (!merchantWallet || !amountPXO) return null;

  return {
    contractAddress,
    chainId: Number(chainIdStr),
    merchantWallet,
    amountPXO,
    label: params.get('label'),
    paymentId: params.get('paymentId'),
  };
}
